- name: Set up Google Cloud
  uses: google-github-actions/setup-gcloud@v2
  with:
    service_account_key: ${{ secrets.GCP_SA_KEY }}
    project_id: ${{ env.PROJECT_ID }}
    export_default_credentials: true

- name: Authenticate Docker for Artifact Registry
  run: |
    gcloud auth configure-docker us-central1-docker.pkg.dev

- name: Build and push Docker image
  run: |
    IMAGE="us-central1-docker.pkg.dev/$PROJECT_ID/spring-run-repo/$SERVICE_NAME"
    docker build -t $IMAGE .
    docker push $IMAGE
